### PR TITLE
Making the app more much smaller.

### PR DESCRIPTION
**Pull request by cloneconf**
I did some optimizations.
like removing most libraries (literally all except appcompat), enabling minify for smaller apk, and some layout changes.

I did built the app and the apk is under 1MB which is good :)

size

### CODE REVIEW

**Comment by woheller69** [comment]
Thanks for your proposal. I am sorry, but I will not merge it.
Half of the advantage comes from "minify". I will not activate "minify" because the code in crash reports is obfuscated and does not help solving bugs.
The other half comes from removing com.google.android.material:material:1.4.0'.
But this comes at the price that the automatic dark mode is no longer working.
Your version also contains lots of deprecated APIs like android.preference instead of androidX.preference. 
I will definitely not downgrade from AndroidX libraries to save a few bytes...

**Comment by cloneconf** [comment]
> Half of the advantage comes from "minify"

this can be simply solved by editting the line in gradle file.

> But this comes at the price that the automatic dark mode is no longer working.

if really are using the material design for only auto dark then this kinda waste.
instead using:
`Theme.AppCompat.Light.NoActionBar`
and
`Theme.AppCompat.DayNight.NoActionBar`
Screenshot_2021-11-06_17-23-50
Screenshot_2021-11-06_17-14-19
but it really up to you here..

> Your version also contains lots of deprecated APIs like android.preference instead of androidX.preference.

you are right.
it should be added.

> I will definitely not downgrade from AndroidX libraries

technically i didn't remove Androidx.
except androidX.preference (yeah it's a mistake) and unused libraries.

> to save a few bytes...

it isn't for that, thought it will be nice, right :)

Best Regards.

**Comment by woheller69** [comment]
I tried the appcompat theme but did not like it. It saved 0.5MB.

Minify: I know, it is one line. And it saves 1.2MB.
But it the app crashes and someone sends a logcat the log is obfuscated and I cannot debug...
Maybe in future if the app is stable in the field and there are no bugs I can activate it.

But nevertheless thanks for the idea!

**Comment by cloneconf** [comment]
Thanks for your respond :)

> I tried the appcompat theme but did not like it. It saved 0.5MB.

it's really your decision ¯\_(ツ)_/¯

> But it the app crashes and someone sends a logcat the log is obfuscated and I cannot debug...

you are building for production use, right?
no one would look to the logcat i guess.

the app crashes?
you can simply add try/catch to handle possible errors
and show a crash screen so the user knows what did go wrong..

**Comment by woheller69** [comment]
yeah, for production of many eggs :-)
For my other apps I got logcats quite often in the beginning and that is very helpful for debugging.
try catch if not my way to handle errors...

**Comment by cloneconf** [comment]
Ok, tbh i did get it.
But if you find the best then go forward ;)

**Pull request closed without merging**
