### PR TITLE
Add notifications permission request

### LINKED ISSUE #32: Android 13
<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>

If the user denies the [notification permission](https://developer.android.com/guide/topics/ui/notifiers/notification-permission), they don't see notices related to foreground services in the [notification drawer](https://developer.android.com/guide/topics/ui/notifiers/notifications#appearances). However, users still see notices related to foreground services in the [Foreground Services (FGS) Task Manager](https://developer.android.com/about/versions/13/changes/fgs-manager), regardless of whether the notification permission is granted.

If you would like the notification to be non-dismissable by the user, pass true into the [setOngoing()](https://developer.android.com/reference/android/app/Notification.Builder#setOngoing(boolean)) method when you create your notification using Notification.Builder.

### PR DESCRIPTION
**Pull request by AndreiShpakovskiy**
This PR resolves #32 by adding runtime Notifications permission request on Android 13+

### CODE REVIEW

**Comment by woheller69** [comment]
Thanks, but this issue is not a real one. It was only some collection of info for me what to do when I upgrade the app to Android 13. So far I do not have an Android 13 device and therefore I will not upgrade the targetSdk. That means I am not going to merge this soon...

But thanks!

Why did you remove this part?

             //SCHEDULE_EXACT_ALARM: on Android 12 this permission is automatically granted by the Android system but on Android 13 we need to check if the user has granted this permission.
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) {
            if (!alarmManager.canScheduleExactAlarms()) {
                Intent intent2 = new Intent();
                intent2.setAction(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM);
                startActivity(intent2);
            }
        }

**Comment by AndreiShpakovskiy** [comment]
I've tried to refactor the app, but quickly realised you are not gonna like it. Didn't notice one part left removed. I'm sorry for this.

**Comment by woheller69** [comment]
That is probably also remaining from refactoring

    private static ActivityResultLauncher<String> notificationPermissionLauncher

I will also move the check permission stuff from MainActivity to Notification as implemented for Location
But first I need an Android 13 device...

**Comment by AndreiShpakovskiy** [comment]
Yeap, my fault.

By the way, it doesn't look like a good idea to move permission request / response handling to non-activity class. It is the responsibility of the activity or fragment to take care of permissions. Now it works just because Context comes directly from activity and it's casted to Activity. You'll not be able to check permission result in non-activity class without tricks I don't really know about.

Also, you can try Android 13 emulator, if you wish. It's not that bad :)

**Comment by woheller69** [comment]
maybe without checking permission result.
Request permission in onCreate and init notification in onResume...

**Comment by AndreiShpakovskiy** [comment]
Well, I've implemented it too. Just in case you need it in the future.

**Comment by woheller69** [comment]
Thanks, I merged it into a new Android13 branch.
Will merge into main when I am ready for Android13

**Pull request merged**
